#+TITLE: Emacs mode for FLE amateur radio logging files

This is Emacs package intended to support [[https://df3cb.com/fle/][Fast Log Entry]] (FLE) text files. The text format is [[https://df3cb.com/fle/documentation/][documented]] online.  Users can optionally use [[https://github.com/on4kjm/FLEcli][FLEcli]] to process FLE formatted files and upload to the user's preferred destination.

* fle-mode

This provides font-lock highlighting for FLE files and rudimentary support for navigation via [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Imenu.html#Imenu][Imenu]].

* Installation

You can either clone this repository and add it your ~load-path~ or use something like /Quelpa/ or /Straight/ to add to your configuration.  The following is one example.

#+begin_src emacs-lisp
(use-package fle-mode
  :straight (fle-mode :type git :host github :repo "sfromm/fle-mode")
  :commands (fle-mode))
#+end_src

* FLE keywords
The following is not intended to replace the [[https://df3cb.com/fle/documentation/][documentation]] maintained by DF3CB.

** Header section
- *mycall*
- *mygrid*
- *operator*
- *qslmsg*
- *mywwff*
- *mysota*
- *mypota*
- *nickname*
** Optional information
- QSO comments must be embedded in brackets =< >=.
- The QSO partner's name must have a preceding =@=.
- Grid locators must have a preceding =#=.
- QSL messages must be embedded in square brackets =[ ]=.
- Remarks can be embedded in curly braces ={ }=.  Remarks are not exported to ADIF.
- Remarks  can also be set in lines that begin with a =#=.
* Future goals

- More fine-tuning of regular expressions.
- +Keybindings to facilitate inserting dates and times.+
- +Function to query QRZ for a call-sign+
  + What about other websites?
- Perhaps invoke ~flecli~ from a /fle/ buffer.

